version: '3.9'
services:
  miner:
    image: fissssssh/miner:v1.1.3
    container_name: miner
    ports:
      - "8080:8080"
    restart: always
    environment:
      MINER_CONNECTIONSTRINGS__REDIS: redis:6379
      MINER_CONNECTIONSTRINGS__MONGODB: mongodb://mongodb:27017
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis
    container_name: redis
    volumes:
      - "./redis/data:/data"
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - "./mongo/db:/data/db"
